### ISSUE TITLE
python-online-auth: rebase on master

### ISSUE THREAD

**Issue by vorburger** [jamesread/prometheus-gmail-exporter#13]
In the context of https://github.com/jamesread/prometheus-gmail-exporter/issues/10, I had a brief try at [the python-online-auth](https://github.com/jamesread/prometheus-gmail-exporter/compare/python-online-auth) branch and noticed it doesn't cleanly rebase to master; perhaps this issue could track sorting out the conflicts?

[My branch here](https://github.com/jamesread/prometheus-gmail-exporter/compare/master...vorburger:prometheus-gmail-exporter:python-online-auth__vorburger) has some WIP progress on that.

The bigger overall priority may be first fixing #12 though.

**Comment by jamesread** [comment]
Hey @vorburger , so sorry for the confusion - I pushed that branch quickly yesterday when I saw you were working on the project, as I didn't want stale code on my machine that might have fixed some things to be lost to any updates you might have made.

As you've probably worked out by now, the master branch already does "online auth" - which should be more correctly called "OAuth inline" I believe - listening on localhost:9090 etc. I previously was doing "out of bound (oob)" OAuth, and the leftovers from that are in the run_flow_oob_deprecated() function. 

This branch wasn't "online-auth" at all, it was me trying to add a `readyz` Kubernetes listening endpoint to the server, so that containers on Kubernetes would run a little nicer. In order to do this I needed to break out the way the Prometheus client was hosting, etc - that's what you can see in the code on this branch.

Moving forward, I've renamed this branch from "python-online-auth" to "kubernetes-readyz-with-wsgi". Really sorry about the confusion.
